parameters:
    websocket_port: '%env(int:WEBSOCKET_PORT)%'
#    size: 1024

services:
#    App\Service\OpenSwoole\Factory\TableFactory:
#        arguments: 
#            $size: '%size%'
    app.openswoole.server:
        class: App\Service\OpenSwoole\WebsocketServer
        arguments:
            $port: '%websocket_port%'
            $fds: '@App\Service\OpenSwoole\Factory\TableFactory'
